# title of website
title: 网址导航

# description of website
description: ylfei's navigation site

# favicon of website
favicon: "https://github.com/ylfei.png?size=40"

# your website url
url: https://ylfei.github.io/web

# github profile url
github: "https://github.com/ylfei/web"

# footer message
footer: Information © 2021-2022 Website by ylf

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - bing
      - sougou
      
      - bilibili
      - zhihu
      

content:
  categories:
    - name: 在线工具
      sites:
        - name: 腾讯文档
          description: 腾讯文档是一款可多人协作的在线文档
          url: https://docs.qq.com/
        - name: 金山文档
          description: 可多人实时协作编辑的在线文档
          url: https://www.kdocs.cn/
        - name: 金山表单
          description: 金山表单是免费的在线表单
          url: https://f.wps.cn/home
        - name: 有道云笔记
          description: 专注办公提效的笔记软件
          url: https://note.youdao.com/
        - name: 一个工具箱
          description: 一个工具箱网站致力于为您打造一个好用便捷的在线工具箱
          url: http://www.atoolbox.net/
        - name:  蛙蛙工具
          description:  便捷的在线工具网站
          url: https://www.iamwawa.cn/
        - name: 问卷星
          description: 问卷调查,调查问卷,在线考试
          url: https://www.wjx.cn/
     
    - name: 电子邮箱
      sites:
        - name: 126邮箱
          description: 网易126免费邮箱--你的专业电子邮局
          url: https://mail.126.com/
        - name: 163邮箱
          description: 网易163免费邮箱--中文邮箱第一品牌
          url: https://mail.163.com/
        - name: QQ邮箱
          description: QQ邮箱是腾讯公司向用户提供安全、稳定、快速、便捷电子邮件服务的邮箱产品
          url: https://mail.qq.com/
        - name: 完美邮箱
          description: 轻松定制个人专业邮箱，免费定制二级域名
          url: https://www.email.cn/
        - name: 腾讯企业邮箱
          description: 腾讯企业邮箱，唯一可以在微信中收发邮件的企业邮箱
          url: https://exmail.qq.com/login/
        - name: Outlook
          description: 来自Microsoft的免费个人电子邮件和日历
          url: https://outlook.live.com/
        - name: 临时邮箱
          description: 临时邮箱、24小时邮箱
          url: http://24mail.chacuo.net/ 
    - name: 影视资源
      sites: 
        - name: 优酷
          description: 视频服务平台,提供视频播放,视频发布,视频搜索,视频分享
          url: https://www.youku.com/
        - name: 爱奇艺
          description: 在线视频网站，海量正版高清视频在线观看
          url: https://www.iqiyi.com/
        - name: 腾讯视频
          description: 在线视频媒体平台，海量高清视频在线观看
          url: https://v.qq.com/
        - name: 哔哩哔哩
          description: bilibili是国内知名的视频弹幕网站，这里有最及时的动漫新番，最棒的ACG氛围，最有创意的Up主
          url: https://www.bilibili.com
        - name: 央视网
          description: 央视网是中央广播电视总台主办的中央重点新闻网站，是拥有全牌照业务资质的大型互联网文化企业
          url: https://tv.cctv.com/
        - name: 央视纪实
          description: 纪实台汇集了央视大量优秀经典纪录片，集纳国内地方台、BBC、国家地理、美国历史频道、NHK等
          url: http://jishi.cctv.com/
        - name: 新点亮视频
          description: 新点亮视频网页版
          url: https://dianliang521.github.io/xindianliangshipin/index.html
        
    - name: 网络存储   
      sites:
        - name: 阿里云盘
          description: 阿里云盘是一款速度快、不打扰、够安全、易于分享的网盘
          url: https://www.aliyundrive.com/
        - name: 天翼云盘
          description: 天翼云盘是中国电信推出的云存储服务，为用户提供跨平台的文件存储、备份、同步及分享服务
          url: https://cloud.189.cn/web/login.html/
        - name: 腾讯微云
          description: 微云是腾讯公司为用户精心打造的一项智能云服务
          url: https://www.weiyun.com/
        - name: 百度网盘
          description: 百度网盘为您提供文件的网络备份、同步和分享服务
          url: https://pan.baidu.com/
        - name: 文叔叔
          description: 传文件，找文叔叔（永不限速）
          url: https://www.wenshushu.cn/
        - name: 永硕E盘
          description: 数据存储、交流平台,可以保存您的文件、网址、记事等
          url: http://www.ys168.com/ 
    - name: 软件工具
      sites:
        - name: MSND
          description: 一个原版软件信息收录站点，该网站创办十年仍是非常简洁的风格
          url: https://msdn.itellyou.cn/
        - name: Office Tool Plus
          description: 基于Office部署工具制作，除此之外还集成了各种实用性工具
          url: https://otp.landian.vip/zh-cn/
        - name: 小鱼儿yr系统
          description: 小鱼儿yr系统专注于WIN7，WIN10，系统封装，封装系统，重装系统，系统教程
          url: https://www.yrxitong.com/
        - name: 果核剥壳
          description: 果核剥壳是一家博客类型的资源分享软件，分享绿色软件软件，安卓软件等
          url: https://www.ghxi.com/
        - name: 腾讯软件中心
          description: 腾讯软件中心提拱海量免费软件安全下载
          url: https://pc.qq.com/
        - name: 小众软件
          description: 小众软件是一个分享、体验、评测电脑软件、手机应用、互联网产品的网站
          url: https://www.appinn.com/
        - name: 大眼仔
          description: 大眼仔旭博客提供各类PC软件,绿色软件,手机游戏,安卓APP,汉化软件,软件教程
          url: http://www.dayanzai.me/
        - name: 正版中国
          description: 以提供正版软件限时免费信息为途径,引导用户养成使用正版软件的习惯,以此促进国内版权氛围的改进
          url: https://www.getitfree.cn/ 
        - name: Ventoy
          description: 新一代多系统启动U盘解决方案
          url: https://www.ventoy.net/cn/index.html
        - name: DLL-FLES
          description: DLL问题解决方案
          url: https://cn.dll-files.com/
        - name: Snipaste
          description: Snipaste-截图 + 贴图
          url: https://zh.snipaste.com/
        - name: TrafficMonitor
          description: 流量监控器
          url: https://github.com/zhongyang219/TrafficMonitor/releases
    - name: 社区资讯  
      sites:
        - name: IT之家
          description: IT科技门户网站。快速精选IT新闻，实时报道科技周边												
          url: https://www.ithome.com/					
        - name: IT天空
          description: 以系统封装技术与驱动技术为主的综合性IT站点
          url: https://www.itsk.com/
        - name: Gitee
          description: Gitee.com(码云) 是 OSCHINA.NET 推出的代码托管平台,支持 Git 和 SVN,提供免费的私有仓库托管
          url: https://gitee.com/
        - name: GitHub
          description: GitHub brings together the world’s largest community of developers to discover.
          url: https://github.com/
        - name: 微博
          description: 随时随地发现新鲜事
          url: https://weibo.com/
        - name: 知乎
          description: 有问题，上知乎。知乎，可信赖的问答社区，以让每个人高效获得可信赖的解答为使命
          url: https://www.zhihu.com/explore#daily-hot/
    - name: 在线课程
      sites:
        - name: 中国大学MOOC
          description: 中国大学MOOC(慕课) 是国内优质的中文MOOC学习平台,由爱课程网携手网易云课堂打造
          url: https://www.icourse163.org/
        - name: 大学资源网
          description: 大学资源网致力于为每个希望提升自己能力的人提供学习平台
          url: http://www.dxzy163.com/
        - name: 北京大学公开课
          description: 北京大学公开课
          url: http://opencourse.pku.edu.cn/course/opencourse2/index.html
        - name: 网易公开课
          description: 网易视频公开课频道推出国内外名校公开课,涉及广泛的学科,名校老师认真讲解深度剖析
          url:  https://open.163.com/
        - name: 腾讯课堂
          description: 腾讯推出的专业在线教育平台，聚合大量优质教育机构和名师
          url:  https://ke.qq.com/
        - name: 菜鸟教程
          description: 菜鸟教程提供了编程的基础技术教程, 介绍了HTML、CSS、Javascript、Python，Java，Ruby，C，PHP , MySQL等各种编程语言的基础知识
          url: https://www.runoob.com/
        - name: w3school
          description: w3school 在线教程
          url: https://www.w3school.com.cn/
    - name: 网页扩展
      sites: 
        - name: Chrome插件
          description: 使用Chrome插件可以为Chrome浏览器带来一些功能性的扩展，进而提高Chrome的使用体验
          url: https://huajiakeji.com/
        - name: Crx4Chrome插件下载
          description: 想要安装Chrome插件的方式有许多，用户可以直接在Chrome商店中下载和安装谷歌浏览器插件
          url: http://www.crx4.com/
        - name: Chrome/谷歌浏览器插件
          description: 分享好用靠谱的，Chrome/谷歌浏览器插件
          url: https://www.chrome666.com/
        - name: 扩展迷
          description: 扩展迷-专业的Chrome插件网,提供Chrome商店/谷歌应用商店里各类Chrome插件下载
          url: https://www.extfans.com/    
        - name: Greasy Fork
          description: Greasy Fork - 安全、实用的用户脚本大全
          url: https://greasyfork.org/zh-CN/scripts/
        - name: Crx搜搜
          description: 浏览器扩展商店
          url: https://www.crxsoso.com/
        - name: CrxDL
          description: 浏览器扩展离线安装包
          url: https://crxdl.com/
    - name: PDF转换
      sites:
        - name: PDF2GO
          description: 免费的在线PDF转换器
          url:  https://www.pdf2go.com/zh
        - name:  iLovePDF
          description: 免费支持15MB的PDF转换
          url: https://www.ilovepdf.com/zh-cn
        - name: ALL TO ALL
          description: 在线格式转换
          url: https://www.alltoall.net
    - name: 在线配色
      sites:
        - name: SDC优设网配色工具
          description: 优设网帮助您完成配色方案，不用配色软件轻松配色
          url: https://color.uisdc.com/
        - name: HTML拾色器
          description: HTML拾色器
          url: https://www.runoob.com/tags/html-colorpicker.html
        - name: 中国传统颜色
          description: 中国传统颜色
          url: http://zhongguose.com/
    - name: 字体资源
      sites: 
        - name: 站长字体
          description: 字体库提供,中文字体下载,英文字体下载,书法字体下载,艺术字体下载,广告字体下载,方正字体下载等字体免费下载
          url: https://font.chinaz.com/
        - name: 找字网
          description: 提供中英文免费字体下载、手写字体下载、书法字体下载、艺术字体下载、手机字体下载预览服务
          url: http://www.zhaozi.cn/
        - name: 猫啃网
          description: 猫啃网致力于为广大设计师提供最新最全且免费的，可商用，无版权问题的免费字体下载
          url: https://www.maoken.com/
        - name: 字体之家
          description: 字体之家提供最全的免费手机字体和手机软件下载,包括各种字体打包下载,中文字体,英文字体,ps字体,艺术字体,手机软件，字体工具等
          url: http://www.17ziti.com/
        - name: 字由
          description: 字由是为设计师量身定做的一款字体下载管理工具
          url: https://www.hellofont.cn/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/     
   
    - name: 网址导航
      sites:
        - name: 程序员导航
          description: CXY521是一个致力于一站式程序员学习工作娱乐导航网站，以让程序员更便捷为使命，始终围绕程序员需求，为程序员提供最新工具导航
          url: https://www.cxy521.com/
        - name: 有趣网站之家
          description: 分享有趣的国内外网站，应用新奇的html5网站
          url: https://youquhome.com/
        - name: 24K导航
          description: 专注全网优质网址、优质资源分享
          url: https://www.24kdh.com/
        - name: 办公网站导航
          description: 办公人员网址导航，办公人员网站导航，专注分享优秀的办公网站、办公软件、工具、素材、技巧、办公资源
          url: http://hao.xuewps.com/
        - name: 阿虚同学的储物间
          description: 实用导航
          url: https://axutongxue.com/
        - name: 科塔学术导航
          description: 提供科研网站导航，网址库等服务
          url: https://site.sciping.com/
        - name: 爱学术导航
          description: 爱学术导航是科研学术信噪比最高的导航站，致力于成为国内领先的科研与学术资源导航平台，为科研人员提供科研网站导航，网址库等服务
          url: https://www.ixsdh.com/
        - name: 考拉新媒体导航
          description: 考拉新媒体导航，新媒体人的专属门户网站
          url: https://www.kaolamedia.com/
        - name: 今日热榜官网
          description: 今日热榜提供各站热榜聚合
          url: https://tophub.today
        - name: 新媒体导航
          description: 工具推荐服务，是一个优秀、绿色、安全、好用的新媒体助手
          url: http://123.meibp.com/
        - name: 自媒体导航
          description: 自媒体操作后台/内容排版/作图工具等
          url: https://dh.hflmwl.com/
        - name: 大数据导航
          description: 大数据导航
          url: http://hao.bigdata.ren/
 
