# title of website
title: 个人导航

# description of website
description: ylongfei's navigation site

# favicon of website
favicon: "https://github.com/ylongfei.png?size=40"

# your website url
url: https://ylongfei.github.io/url.github.io/

# github profile url
github: "https://github.com/ylongfei"

# footer message
footer: © 2019-2022 @longfei

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - bing
      - github
      - weibo
      - bilibili
      - zhihu

content:
  categories:
    - name: 影视资源
      sites:
        - name: 哔哩哔哩
          description: bilibili是国内知名的视频弹幕网站，这里有最及时的动漫新番，最棒的ACG氛围，最有创意的Up主。
          url: https://www.bilibili.com/
        - name: 爱奇艺
          description: 在线视频网站，海量正版高清视频在线观看。
          url: https://www.iqiyi.com/
        - name: 腾讯视频
          description: 在线视频媒体平台，海量高清视频在线观看。
          url: https://v.qq.com/
        - name: 优酷
          description: 视频服务平台,提供视频播放,视频发布,视频搜索,视频分享。
          url: https://www.youku.com/
        - name: 央视网
          description: 央视网是中央广播电视总台主办的中央重点新闻网站，是拥有全牌照业务资质的大型互联网文化企业。
          url: https://tv.cctv.com/
              
    - name: 电子邮箱
      sites:
        - name: 126邮箱
          description: 网易126免费邮箱--你的专业电子邮局。20年邮箱运营经验，系统快速稳定，垃圾邮件拦截率超过98%，邮箱容量自动翻倍，支持高达3G超大附件，提供免费网盘及手机号码邮箱服务。
          url: https://mail.126.com/
        - name: 163邮箱
          description: 网易163免费邮箱--中文邮箱第一品牌。容量自动翻倍，支持50兆附件,免费开通手机号码邮箱赠送3G超大附件服务。支持各种客户端软件收发，垃圾邮件拦截率超过98%。
          url: https://mail.163.com/
        - name: 新浪邮箱
          description: 新浪邮箱，提供以@sina.com和@sina.cn为后缀的免费邮箱。2G超大附件和50M普通附件，容量5G至无限大，整合新浪微博应用，支持客户端收发，更加安全，更少垃圾邮件。
          url: https://mail.sina.com.cn/
        - name: QQ邮箱
          description: QQ邮箱是腾讯公司2002年推出，向用户提供安全、稳定、快速、便捷电子邮件服务的邮箱产品，已为超过1亿的邮箱用户提供免费和增值邮箱服务。
          url: https://mail.qq.com/
    - name: 网络云盘   
      sites:
        - name: 阿里云盘
          description: 阿里云盘是一款速度快、不打扰、够安全、易于分享的网盘，你可以在这里存储、管理和探索内容，尽情打造丰富的数字世界。
          url: https://www.aliyundrive.com/
        - name: 超星云盘
          description: 不限速，免费空间100G，客户端上传单文件上限15G
          url: https://passport2.chaoxing.com/login?fid=&refer=/
        - name: 腾讯微云
          description: 微云是腾讯公司为用户精心打造的一项智能云服务, 您可以通过微云方便地在手机和电脑之间同步文件、推送照片和传输数据。
          url: https://www.weiyun.com/
        - name: 天翼云盘
          description: 天翼云盘是中国电信推出的云存储服务，为用户提供跨平台的文件存储、备份、同步及分享服务，是国内领先的免费网盘，安全、可靠、稳定、快速。
          url: https://cloud.189.cn/web/login.html/
        - name: 百度网盘
          description: 百度网盘为您提供文件的网络备份、同步和分享服务。空间大、速度快、安全稳固，支持教育网加速，支持手机端。现在注册即有机会享受15G的免费存储空间
          url: https://pan.baidu.com/
        - name: 115网盘
          description: 115社区，你的网上家园。
          url: https://115.com/
        - name: 永硕E盘
          description: 数据存储、交流平台,可以保存您的文件、网址、记事等。
          url: http://www.ys168.com/
    - name: 社区资讯  
      sites:
        - name: IT之家
          description: IT之家，青岛软媒旗下，IT科技门户网站。快速精选IT新闻，实时报道科技周边，关注苹果iOS、谷歌Android、微软Windows Phone，紧盯iPhone/iPad、安卓智能设备、WP手机等数码潮流。技术资讯、攻略教程、资源下载 - IT人的生活，尽在IT之家，爱IT，爱这里。												
          url: https://www.ithome.com/					
        - name: IT天空
          description: 以系统封装技术与驱动技术为主的综合性IT站点,提供完善的系统批量部署解决方案、易用的离线万能驱动和适合装机技术员的U盘PE。
          url: https://www.itsk.com/
        - name: Gitee
          description: Gitee.com(码云) 是 OSCHINA.NET 推出的代码托管平台,支持 Git 和 SVN,提供免费的私有仓库托管。目前已有超过 600 万的开发者选择 Gitee。
          url: https://gitee.com/
        - name: GitHub
          description: GitHub brings together the world’s largest community of developers to discover, share, and build better software. From open source projects to private team repositories, we’re your all-in-one platform for collaborative development.
          url: https://github.com/		
        - name: 知乎
          description: 有问题，上知乎。知乎，可信赖的问答社区，以让每个人高效获得可信赖的解答为使命。
          url: https://www.zhihu.com/explore#daily-hot/
        - name: 豆瓣
          description: 提供图书、电影、音乐唱片的推荐、评论和价格比较，以及城市独特的文化生活。
          url: https://www.douban.com/
   
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: easyicon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.net/
    
    - name: 平面素材
      sites:
        - name: 365PSD
          description: Free PSD & Graphics, Illustrations
          url: https://365psd.com/
        - name: Medialoot
          description: Free & Premium Design Resources — Medialoot
          url: https://medialoot.com/
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/
        - name: 千库网
          description: 免费png图片背景素材下载
          url: http://588ku.com/
        - name: 我图网
          description: 我图网,提供图片素材及模板下载,专注正版设计作品交易
          url: http://www.ooopic.com/
        - name: 90设计
          description: 电商设计（淘宝美工）千图免费淘宝素材库
          url: http://90sheji.com/
        - name: 昵图网
          description: 原创素材共享平台
          url: http://www.nipic.com/
        - name: 懒人图库
          description: 懒人图库专注于提供网页素材下载
          url: http://www.lanrentuku.com/
        - name: 素材搜索
          description: 设计素材搜索聚合
          url: http://so.ui001.com/
        - name: PS饭团网
          description: 不一样的设计素材库！让自己的设计与众不同！
          url: http://psefan.com/
        - name: 素材中国
          description: 免费素材共享平台
          url: http://www.sccnn.com/
    - name: 字体资源
      sites:
        - name: 猫啃网
          description: 猫啃网致力于为广大设计师提供最新最全且免费的，可商用，无版权问题的免费字体下载。
          url: https://www.maoken.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 字体之家
          description: 字体之家提供最全的免费手机字体和手机软件下载,包括各种字体打包下载,中文字体,英文字体,ps字体,艺术字体,手机软件，字体工具等,专注于为网民提供字体下载服务
          url: http://www.17ziti.com/
        - name: 字魂网
          description: 字魂网是一家提供商用字体下载授权,字体定制,免费字体下载,字体授权,以及在线字体转换器的字体公司，致力于让所有人用得起正版字体.
          url: https://izihun.com/
        - name: 站长字体
          description: 字体库提供,中文字体下载,英文字体下载,书法字体下载,繁体字体下载,艺术字体下载,广告字体下载,方正字体下载,草书字体下载,毛笔字体下载,字体设计下载,书法字体下载,字体库,等字体免费下载
          url: https://font.chinaz.com/
        - name: 找字网
          description: 提供中英文免费字体下载、手写字体下载、书法字体下载、艺术字体下载、手机字体下载预览服务！字体商用在线全自动授权！老牌专业字体市场、字体网站。
          url: http://www.zhaozi.cn/
        - name: 字由
          description: 字由是为设计师量身定做的一款字体下载管理工具。这里收集了国内外上千款精选字体，不仅让你轻松、自由和高效的使用字体，还为你展示了每款字体的详细信息和精选的字体文章。
          url: https://www.hellofont.cn/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/
  
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
       
    - name: 在线配色
      sites:
        - name: 炫酷配色
          description: 设计师配色神器
          url: https://www.coocolors.com/
        - name: SDC优设网配色工具
          description: 优设网帮助您完成配色方案，不用配色软件轻松配色。是网页配色、设计师配色的实用网页配色工具。
          url: https://color.uisdc.com/
        - name: HTML拾色器
          description: HTML拾色器
          url: https://www.runoob.com/tags/html-colorpicker.html
        - name: 中国传统颜色
          description: 中国传统颜色
          url: http://zhongguose.com/
        - name: 颜色表大全
          description: 颜色表大全
          url: https://www.5tu.cn/colors/yansebiao.html
        - name: trianglify
          description: Trianglify Generator
          url: http://qrohlf.com/trianglify-generator/
        - name: klart
          description: Beautiful colors and designs to your inbox every week
          url: https://klart.co/colors/
        - name: vanschneider
          description: Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects.
          url: http://www.vanschneider.com/colors
    - name: 在线工具
      sites:
        - name: 在线工具
          description: 程序员的工具箱，代码格式化、压缩、加密、解密等
          url: https://tool.lu/
        - name: 一个工具箱
          description: 一个工具箱网站致力于为您打造一个好用便捷的在线工具箱，无需注册和下载安装即可免费使用各种在线工具，涉及加密解密、文字编辑、编程开发、单位换算、日期时间、图形图像、金融服务、日常生活、查询服务等诸多种类的在线工具。
          url: http://www.atoolbox.net/
        - name: MikuTools
          description: 一个轻量的工具集合
          url: https://tools.miku.ac/
    - name: 在线课程
      sites:
        - name: 我要自学网
          description: 我要自学网提供免费视频教程,提供全方位软件学习，有3D教程，平面教程，多媒体制作教程，办公信息化教程，机械设计教程，网站制作教程,电脑培训
          url: https://www.51zxw.net/
        - name: 大学资源网
          description: 大学资源网致力于为每个希望提升自己能力的人提供学习平台，通过这个平台每个人都有平等提高自己能力的机会，主要学习资源有：大学课程、中学课程、小学课程、管理课程培训等视频教程！
          url: http://www.dxzy163.com/
        - name: w3school
          description: w3school 在线教程
          url: https://www.w3school.com.cn/
        - name: 菜鸟教程
          description: 菜鸟教程提供了编程的基础技术教程, 介绍了HTML、CSS、Javascript、Python，Java，Ruby，C，PHP , MySQL等各种编程语言的基础知识
          url: https://www.runoob.com/
        - name: 爱课程
          description: “爱课程”网是教育部、财政部“十二五”期间启动实施的“高等学校本科教学质量与教学改革工程”委托高等教育出版社建设的高等教育课程资源共享平台。旨在利用现代信息技术和网络技术，推动高校的教育教学改革，提高高等教育质量，以公益性为本，构建可持续发展机制，为高校、师生和社会学习者提供优质教育资源共享和个性化教学服务。
          url: https://www.icourses.cn/home/
        - name: 中国大学MOOC
          description: 中国大学MOOC(慕课) 是国内优质的中文MOOC学习平台,由爱课程网携手网易云课堂打造。
          url: https://www.icourse163.org/
        - name: 腾讯课堂
          description: 腾讯推出的专业在线教育平台，聚合大量优质教育机构和名师，下设职业培训、公务员考试、托福雅思、考证考级、英语口语、中小学教育等众多在线学习精品课程，打造老师在线上课教学、学生及时互动学习的课堂。腾讯课堂，学习成就梦想！
          url: https://ke.qq.com/
    - name: 设计电台
      sites:
        - name: UX Coffee
          description: 《UX Coffee 设计咖》是一档关于用户体验的播客节目。我们邀请来自硅谷和国内的学者和职人来聊聊「产品设计」、「用户体验」和「个人成长」。
          url: http://uxcoffee.co/
        - name: Anyway.FM
          description: 设计杂谈 • UI 设计师 JJ 和 Leon 主播的设计播客
          url: https://anyway.fm/
        - name: 异能电台
          description: 将全宇宙设计师的故事讲给你听。
          url: https://www.yineng.fm
    - name: 网址导航
      sites:
        - name: 程序员导航
          description: CXY521是一个致力于一站式程序员学习工作娱乐导航网站，以让程序员更便捷为使命，始终围绕程序员需求，为程序员提供最新工具导航
          url: https://www.cxy521.com/
        - name: 有趣网站之家
          description: 分享有趣的国内外网站，应用新奇的html5网站
          url: https://youquhome.com/
        - name: 24K导航
          description: 专注全网优质网址、优质资源分享。
          url: https://www.24kdh.com/
        - name: 办公网站导航
          description: 办公人员网址导航，办公人员网站导航，专注分享优秀的办公网站、办公软件、工具、素材、技巧、办公资源
          url: http://hao.xuewps.com/
        - name: 阿虚同学的储物间
          description: 实用导航
          url: https://axutongxue.com/
        - name: 科塔学术导航
          description: 提供科研网站导航，网址库等服务
          url: https://site.sciping.com/
        - name: 爱学术导航
          description: 爱学术导航是科研学术信噪比最高的导航站，致力于成为国内领先的科研与学术资源导航平台，为科研人员提供科研网站导航，网址库等服务，让科研工作更简单、更有效率。
          url: https://www.ixsdh.com/
 
