# title of website
title: 个人导航

# description of website
description: ylongfei's navigation site

# favicon of website
favicon: "https://github.com/ylongfei.png?size=40"

# your website url
url: https://ylongfei.github.io/url.github.io/

# github profile url
github: "https://github.com/ylongfei"

# footer message
footer: © 2019-2021 @ylongfei

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - github
      - weibo
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
      
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 猎云网
          description: 互联网创业项目推荐和创业创新资讯
          url: http://www.lieyunwang.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
      
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
      
    - name: 网页灵感
      sites:
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
        - name: CSS Design Awards
          description: Website Awards & Inspiration - CSS Gallery
          url: https://www.cssdesignawards.com/
        - name: The FWA
          description: FWA - showcasing innovation every day since 2000
          url: https://thefwa.com/
        - name: Ecommercefolio
          description: Only the Best Ecommerce Design Inspiration
          url: http://www.ecommercefolio.com/
       
        - name: Pages
          description: Curated directory of the best Pages
          url: http://www.pages.xyz/
      
        - name: WebInspiration
          description: 网页设计欣赏,全球顶级网页设计
          url: http://web.uedna.com/
        - name: navnav
          description: A ton of CSS, jQuery, and JavaScript responsive navigation examples, demos, and tutorials from all over the web.
          url: http://navnav.co/
        - name: Really Good UX
          description: A library of screenshots and examples of really good UX. Brought to you by
          url: https://www.reallygoodux.io/
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: easyicon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.net/
    
    - name: 平面素材
      sites:
        
        - name: 365PSD
          description: Free PSD & Graphics, Illustrations
          url: https://365psd.com/
        - name: Medialoot
          description: Free & Premium Design Resources — Medialoot
          url: https://medialoot.com/
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/
        - name: 千库网
          description: 免费png图片背景素材下载
          url: http://588ku.com/
        - name: 我图网
          description: 我图网,提供图片素材及模板下载,专注正版设计作品交易
          url: http://www.ooopic.com/
        - name: 90设计
          description: 电商设计（淘宝美工）千图免费淘宝素材库
          url: http://90sheji.com/
        - name: 昵图网
          description: 原创素材共享平台
          url: http://www.nipic.com/
        - name: 懒人图库
          description: 懒人图库专注于提供网页素材下载
          url: http://www.lanrentuku.com/
        - name: 素材搜索
          description: 设计素材搜索聚合
          url: http://so.ui001.com/
        - name: PS饭团网
          description: 不一样的设计素材库！让自己的设计与众不同！
          url: http://psefan.com/
        - name: 素材中国
          description: 免费素材共享平台
          url: http://www.sccnn.com/
        
    - name: UI资源
      sites:
        - name: Freebiesbug
          description: Hand-picked resources for web designer and developers, constantly updated.
          url: https://freebiesbug.com/
        - name: Freebie Supply
          description: Free Resources For Designers
          url: https://freebiesupply.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: 稀土区
          description: 优质设计开发资源分享
          url: https://xituqu.com/
        - name: UIkit.me
          description: 最便捷新鲜的uikit资源下载网站
          url: http://www.uikit.me/
    - name: Sketch资源
      sites:
       
        - name: Sketch.im
          description: Sketch 相关资源汇聚
          url: http://www.sketch.im/
        - name: Sketch Hunt
          description: Sketch Hunt is an independent blog sharing gems in learning, plugins & design tools for fans of Sketch app.
          url: http://sketchhunt.com/
        - name: Sketch中文网
          description: 分享最新的Sketch中文手册
          url: http://www.sketchcn.com/
        - name: Awesome Sketch Plugins
          description: A collection of really useful Sketch plugins.
          url: https://awesome-sket.ch/
        - name: Sketchcasts
          description: Learn Sketch Train your design skills with a weekly video tutorial
          url: https://www.sketchcasts.net/
        - name: Sketch
          description: The digital design toolkit
          url: https://sketchapp.com/
    - name: 字体资源
      sites:
        - name: Google Font
          description: Making the web more beautiful, fast, and open through great typography
          url: https://fonts.google.com/
        - name: Typekit
          description: Quality fonts from the world’s best foundries.
          url: https://typekit.com/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/
        - name: Fontsquirrel
          description: FREE fonts for graphic designers
          url: https://www.fontsquirrel.com/
        - name: Urban Fonts
          description: Download Free Fonts and Free Dingbats.
          url: https://www.urbanfonts.com/
        - name: Lost Type
          description: Lost Type is a Collaborative Digital Type Foundry
          url: http://www.losttype.com/
        - name: FONTS2U
          description: Download free fonts for Windows and Macintosh.
          url: https://fonts2u.com/
        - name: Fontex
          description: Free Fonts to Download + Premium Typefaces
          url: http://www.fontex.org/

        
  
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
      
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: 图形创意
      sites:
        - name: photoshop
          description: Photoshop不需要解释
          url: https://www.adobe.com/cn/products/photoshop.html
        - name: Affinity Designer
          description: 专业创意软件
          url: https://affinity.serif.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
        - name: cinema-4d
          description: Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free.
          url: https://www.maxon.net/en/products/cinema-4d/overview/
        - name: 3ds-max
          description: 3D modeling, animation, and rendering software
          url: https://www.autodesk.com/products/3ds-max/overview
        - name: Blender
          description: Blender is the free and open source 3D creation suite.
          url: https://www.blender.org/
    - name: 界面设计
      sites:
        - name: Adobe XD
          description: Introducing Adobe XD. Design. Prototype. Experience.
          url: http://www.adobe.com/products/xd.html
        - name: invisionapp
          description: Powerful design prototyping tools
          url: https://www.invisionapp.com/
        - name: marvelapp
          description: Simple design, prototyping and collaboration
          url: https://marvelapp.com/
        - name: Muse CC
          description: 无需利用编码即可进行网站设计。
          url: https://creative.adobe.com/zh-cn/products/download/muse
        - name: figma
          description: Design, prototype, and gather feedback all in one place with Figma.
          url: https://www.figma.com/

    - name: 在线配色
      sites:
        
        - name: trianglify
          description: Trianglify Generator
          url: http://qrohlf.com/trianglify-generator/
        - name: klart
          description: Beautiful colors and designs to your inbox every week
          url: https://klart.co/colors/
        - name: vanschneider
          description: Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects.
          url: http://www.vanschneider.com/colors
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
       
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
   
    - name: 视频教程
      sites:
        - name: Photoshop Lady
          description: Your Favourite Photoshop Tutorials in One Place
          url: http://www.photoshoplady.com/
        - name: doyoudo
          description: 创意设计软件学习平台
          url: http://doyoudo.com/
        - name: 没位道
          description: WEB UI免费视频公开课
          url: http://www.c945.com/web-ui-tutorial/
        - name: 慕课网
          description: 程序员的梦工厂（有UI课程）
          url: https://www.imooc.com/
    - name: 设计文章
      sites:
        - name: Web Design Ledger
          description: Web Design Blog
          url: https://webdesignledger.com
    - name: 设计电台
      sites:
        - name: UX Coffee
          description: 《UX Coffee 设计咖》是一档关于用户体验的播客节目。我们邀请来自硅谷和国内的学者和职人来聊聊「产品设计」、「用户体验」和「个人成长」。
          url: http://uxcoffee.co/
        - name: Anyway.FM
          description: 设计杂谈 • UI 设计师 JJ 和 Leon 主播的设计播客
          url: https://anyway.fm/
        - name: 异能电台
          description: 将全宇宙设计师的故事讲给你听。
          url: https://www.yineng.fm
    - name: 交互设计
      sites:
        - name: Little Big Details
          description: Little Big Details is a curated collection of the finer details of design, updated every day.
          url: http://littlebigdetails.com/
        - name: Smashing Magazine
          description: Below you’ll find the best tips to take not only your UX design process but also the experiences you craft to the next level.
          url: https://www.smashingmagazine.com/category/user-experience
        - name: nngroup
          description: Evidence-Based User Experience Research, Training, and Consulting
          url: https://www.nngroup.com/articles/
        - name: Boxes and Arrows
          description: Boxes and Arrows is devoted to the practice, innovation, and discussion of design; including graphic design, interaction design, information architecture and the design of business.
          url: http://boxesandarrows.com/
        - name: UX Design Weekly
          description: get a hand picked list of the best user experience design links every week.
          url: http://uxdesignweekly.com/
        - name: UX Ren
          description: 用户体验人的专业社区
          url: http://uxren.cn/
    - name: UED团队
      sites:
        
        - name: 腾讯CDC
          description: 腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。
          url: http://cdc.tencent.com/
        - name: TGideas
          description: TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队
          url: http://tgideas.qq.com/
        - name: ISUX
          description: 腾讯社交用户体验设计部
          url: https://isux.tencent.com/
        - name: MXD
          description: 腾讯MIG无线互联网事业群设计团队
          url: http://mxd.tencent.com/
        - name: Aliued
          description: 阿里巴巴国际UED团队
          url: http://www.aliued.com/
        - name: U一点
          description: 阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队
          url: http://www.aliued.cn/
        - name: 网易uedc
          description: 网易用户体验设计中心（User Experience Design Center）
          url: http://uedc.163.com/
        - name: 百度用户体验中心
          description: 百度用户体验中心
          url: http://ued.baidu.com/
        - name: 京东设计中心
          description: 京东设计中心
          url: http://jdc.jd.com/
        - name: 百度企业产品用户体验中心
          description: 百度企业产品用户体验中心
          url: http://eux.baidu.com/
        - name: 
          url: 
